name: Build on Arch Linux
on: push

jobs:
  build:
	name: Build on Arch Linux
	runs-on: ubuntu-latest
	container:
	  image: archlinux:base-devel
	  volumes:
		- ${{ github.workspace }}:/app
	steps:
	  - name: Checkout the repo
		uses: actions/checkout@v3
	  - name: Install Dependencies
		run: sudo pacman -Syy
