name: Build on Arch Linux
on: push

jobs:
  build:
    name: Build on Arch Linux
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pull Docker Image
        run: docker pull archlinux:base-devel
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Steps in New Container
        run: |
          docker run --rm -v ${{ github.workspace }}:/app archlinux:base-devel bash -c '
            # Install build deps
            pacman -Syu cmake vulkan-headers vulkan-validation-layers shaderc glfw-x11 glm rustup --noconfirm
            rustup default stable

            # Run Build
            cd /app && mkdir build && cd build
            cmake ..
            make
          '

          # Additional commands within the container if needed

