name: Build on Arch Linux
on: push

jobs:
  build:
    name: Build on Arch Linux
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pull Docker Image
        run: docker pull archlinux:base-devel
      - name: Run Steps in New Container
        run: |
          docker run --rm -v ${{ github.workspace }}:/app archlinux:base-devel bash -c '
            # Commands to run within the new container
            pacman -Syu --noconfirm
            # Add more commands as needed
          '
